SELECT a.AUTHOR_ID,
       c.AUTHOR_NAME,
       a.CATEGORY,
       SUM(a.PRICE * b.SALES) AS TOTAL_SALES
FROM BOOK a
JOIN BOOK_SALES b
  ON a.BOOK_ID = b.BOOK_ID
JOIN AUTHOR c
  ON a.AUTHOR_ID = c.AUTHOR_ID
WHERE DATE_FORMAT(b.SALES_DATE, '%Y%m') = '202201'
GROUP BY a.AUTHOR_ID, c.AUTHOR_NAME, a.CATEGORY
ORDER BY a.AUTHOR_ID ASC, a.CATEGORY DESC;
