SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT FROM ONLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, '%Y%m') = '202203'
UNION
SELECT SALES_DATE, PRODUCT_ID, NULL, SALES_AMOUNT FROM OFFLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, '%Y%m') = '202203'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID