WITH RENTAL_DURATION AS (
    SELECT 
        HISTORY_ID,
        DAILY_FEE,
        DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION,
        CASE 
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE '할인없음' 
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
)

SELECT 
    R.HISTORY_ID,
    TRUNCATE(R.DAILY_FEE * R.DURATION * (1 - IFNULL(P.DISCOUNT_RATE, 0) / 100), 0) AS FEE
FROM RENTAL_DURATION R
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
    ON R.DURATION_TYPE = P.DURATION_TYPE AND P.CAR_TYPE = '트럭'
ORDER BY FEE DESC, R.HISTORY_ID DESC;