-- 코드를 작성해주세요
select YEAR(a.DIFFERENTIATION_DATE) as YEAR, (b.MAX_SIZE_OF_COLONY - a.SIZE_OF_COLONY) as YEAR_DEV, a.ID from ECOLI_DATA a
join (
    select YEAR(DIFFERENTIATION_DATE) as YEAR, max(SIZE_OF_COLONY) as MAX_SIZE_OF_COLONY from ECOLI_DATA
    group by YEAR(DIFFERENTIATION_DATE)
) b on YEAR(a.DIFFERENTIATION_DATE) = b.YEAR

order by YEAR, YEAR_DEV